<div id="footer_content" class="av-layout-grid-container entry-content-wrapper footer_color av-flex-cells  avia-builder-el-0  el_before_av_one_full  avia-builder-el-first  container_wrap fullsize">
    <div class="flex_cell no_margin av_one_half  avia-builder-el-1  el_before_av_cell_one_half  avia-builder-el-first   av-zero-padding " style="vertical-align:top; padding:0px; "><div class="flex_cell_inner">
            <div class="flex_column av_one_third  no_margin flex_column_div av-zero-column-padding first  avia-builder-el-2  el_before_av_one_third  avia-builder-el-first  " style="margin-top:50px; margin-bottom:50px; border-radius:0px; "><div style="padding-bottom:10px;" class="av-special-heading av-special-heading-h5  blockquote modern-quote  avia-builder-el-3  el_before_av_textblock  avia-builder-el-first  "><h5 class="av-special-heading-tag" itemprop="headline">友情链接</h5><div class="special-heading-border"><div class="special-heading-inner-border"></div></div></div>
                <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " style="font-size:14px; " itemprop="text"><p><a href="#">留学中介</a></p>
                        <p><a href="#">找学校导航网</a></p>
                        <p><a href="#">上海留学中介</a></p>
                        <p><a href="#">澳德华移民</a></p>
                        <p><a href="#">上海国际学校</a></p>
                    </div></section></div><div class="flex_column av_one_third  no_margin flex_column_div av-zero-column-padding   avia-builder-el-5  el_after_av_one_third  el_before_av_one_third  " style="margin-top:50px; margin-bottom:50px; border-radius:0px; "><div style="padding-bottom:10px;" class="av-special-heading av-special-heading-h5  blockquote modern-quote  avia-builder-el-6  el_before_av_textblock  avia-builder-el-first  "><h5 class="av-special-heading-tag" itemprop="headline">留学益网分支机构</h5><div class="special-heading-border"><div class="special-heading-inner-border"></div></div></div>
                <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " style="font-size:14px; " itemprop="text"><p><a href="#">益网北京</a></p>
                        <p><a href="#">益网悉尼</a></p>
                        <p><a href="#">益网墨尔本</a></p>
                        <p><a href="#">益网霍巴特</a></p>
                    </div></section></div><div class="flex_column av_one_third  no_margin flex_column_div av-zero-column-padding   avia-builder-el-8  el_after_av_one_third  avia-builder-el-last  " style="margin-top:50px; margin-bottom:50px; border-radius:0px; "><div style="padding-bottom:10px;" class="av-special-heading av-special-heading-h5  blockquote modern-quote  avia-builder-el-9  el_before_av_textblock  avia-builder-el-first  "><h5 class="av-special-heading-tag" itemprop="headline">关于我们</h5><div class="special-heading-border"><div class="special-heading-inner-border"></div></div></div>
                <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " style="font-size:14px; " itemprop="text"><p><a href="#">顾问团队</a></p>
                        <p><a href="#">服务合约</a></p>
                        <p><a href="#">诚聘英才</a></p>
                        <p><a href="#">益网微博</a></p>
                    </div></section></div></div></div><div class="flex_cell no_margin av_one_half  avia-builder-el-11  el_after_av_cell_one_half  avia-builder-el-last   av-zero-padding " style="vertical-align:top; padding:0px; "><div class="flex_cell_inner">
            <div class="flex_column av_one_third  no_margin flex_column_div av-zero-column-padding first  avia-builder-el-12  el_before_av_one_third  avia-builder-el-first  " style="margin-top:50px; margin-bottom:50px; border-radius:0px; "><div style="padding-bottom:10px;" class="av-special-heading av-special-heading-h5  blockquote modern-quote  avia-builder-el-13  el_before_av_textblock  avia-builder-el-first  "><h5 class="av-special-heading-tag" itemprop="headline">联系我们</h5><div class="special-heading-border"><div class="special-heading-inner-border"></div></div></div>
                <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock  av_inherit_color" style="font-size:14px; color:#a1b1ed; " itemprop="text"><p><span style="font-size: 24pt;"><strong>400-997-1573</strong></span></p>
                        <p>周一至周六（9:00 – 18:00）</p>
                    </div></section>
                <div class="avia-button-wrap avia-button-left  avia-builder-el-15  el_after_av_textblock  avia-builder-el-last "><a href="#" class="avia-button  avia-icon_select-yes-left-icon avia-color-custom avia-size-large avia-position-left " target="_blank" style="background-color:#f36510; border-color:#f36510; color:#ffffff; "><span class="avia_button_icon avia_button_icon_left " aria-hidden="true" data-av_icon="" data-av_iconfont="fontello"></span><span class="avia_iconbox_title">QQ在线咨询</span></a></div></div><div class="flex_column av_one_third  no_margin flex_column_div   avia-builder-el-16  el_after_av_one_third  el_before_av_one_third  " style="margin-top:50px; margin-bottom:50px; padding:20px 0px 0px 0px ; border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-17  avia-builder-el-no-sibling  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="http://localhost/cstudy/wp-content/uploads/2017/03/csa_footer03.png" alt="" title="csa_footer03" itemprop="thumbnailUrl"></div></div></div><div class="flex_column av_one_third  no_margin flex_column_div   avia-builder-el-18  el_after_av_one_third  avia-builder-el-last  " style="margin-top:50px; margin-bottom:50px; padding:20px 0px 0px 0px ; border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-19  avia-builder-el-no-sibling  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="http://localhost/cstudy/wp-content/uploads/2017/03/csa_footer04.png" alt="" title="csa_footer04" itemprop="thumbnailUrl"></div></div></div></div></div></div>