<?php if (!is_front_page()): ?>
<div id="our_humble" class="av-layout-grid-container entry-content-wrapper main_color av-flex-cells  avia-builder-el-0  avia-builder-el-no-sibling  container_wrap fullsize">
    <div class="flex_cell no_margin av_one_full  avia-builder-el-1  avia-builder-el-no-sibling   " style="vertical-align:top; padding:30px 0px 30px 0px ; background-color:#f7f7f7; "><div class="flex_cell_inner">
            <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock  av_inherit_color" style="font-size:16px; color:#333333; " itemprop="text"><p style="text-align: center;"><span style="font-size: 18pt;"><strong><span style="color: #f36410;">低调的我们</span></strong></span></p>
                    <p style="text-align: center;">不求广告铺天盖地，只盼免费服务能够帮到你！</p>
                </div></section>
            <div class="flex_column_table av-equal-height-column-flextable" style="margin-top:30px; margin-bottom:30px; "><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding first  avia-builder-el-3  el_after_av_textblock  el_before_av_one_fifth  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-4  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_014.png" alt="" title="csa_2_014" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">￥0押金、￥0中介费、无风险</span></p>
                        </div></section></div><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding   avia-builder-el-6  el_after_av_one_fifth  el_before_av_one_fifth  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-7  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_015.png" alt="" title="csa_2_015" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">100%教育部认可澳洲学校</span></p>
                        </div></section></div><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding   avia-builder-el-9  el_after_av_one_fifth  el_before_av_one_fifth  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-10  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_016.png" alt="" title="csa_2_016" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">&nbsp;1VS1资深海归顾问辅导</span></p>
                        </div></section></div><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding   avia-builder-el-12  el_after_av_one_fifth  el_before_av_one_fifth  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-13  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_017.png" alt="" title="csa_2_017" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">微信公众号随时随地查询<br>
申请进度</span></p>
                        </div></section></div><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding   avia-builder-el-15  el_after_av_one_fifth  el_before_av_one_fifth  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-16  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_018.png" alt="" title="csa_2_018" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">北京、悉尼、墨尔本、霍巴特<br>
四地为您服务&nbsp;</span></p>
                        </div></section></div></div><!--close column table wrapper. Autoclose:  --><div class="flex_column_table av-equal-height-column-flextable" style="margin-top:30px; margin-bottom:30px; "><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding first  avia-builder-el-18  el_after_av_one_fifth  el_before_av_one_fifth  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-19  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_019.png" alt="" title="csa_2_019" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">完善落地服务</span></p>
                        </div></section></div><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding   avia-builder-el-21  el_after_av_one_fifth  el_before_av_one_fifth  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-22  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_020.png" alt="" title="csa_2_020" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">澳洲升学转学服务</span></p>
                        </div></section></div><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding   avia-builder-el-24  el_after_av_one_fifth  el_before_av_one_fifth  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-25  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_021.png" alt="" title="csa_2_021" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">澳洲续签服务</span></p>
                        </div></section></div><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding   avia-builder-el-27  el_after_av_one_fifth  el_before_av_one_fifth  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-28  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_022.png" alt="" title="csa_2_022" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">后期移民指导及申请</span></p>
                        </div></section></div><div class="flex_column av_one_fifth  no_margin flex_column_table_cell av-equal-height-column av-align-top av-zero-column-padding   avia-builder-el-30  el_after_av_one_fifth  avia-builder-el-last  column-top-margin" style="border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-31  el_before_av_textblock  avia-builder-el-first  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/04/csa_2_023.png" alt="" title="csa_2_023" itemprop="thumbnailUrl"></div></div>
                    <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " itemprop="text"><p style="text-align: center;"><span style="font-family: helvetica, arial, sans-serif;">起源澳洲，执行远超过中国标准<br>
的职业道德和职业操守</span></p>
                        </div></section></div></div><!--close column table wrapper. Autoclose:  --></div></div></div>
<?php endif; ?>
<div id="footer_content" class="av-layout-grid-container entry-content-wrapper footer_color av-flex-cells  avia-builder-el-0  el_before_av_one_full  avia-builder-el-first  container_wrap fullsize">
    <div class="flex_cell no_margin av_one_half  avia-builder-el-1  el_before_av_cell_one_half  avia-builder-el-first   av-zero-padding " style="vertical-align:top; padding:0px; "><div class="flex_cell_inner">
            <div class="flex_column av_one_third  no_margin flex_column_div av-zero-column-padding first  avia-builder-el-2  el_before_av_one_third  avia-builder-el-first  " style="margin-top:50px; margin-bottom:50px; border-radius:0px; "><div style="padding-bottom:10px;" class="av-special-heading av-special-heading-h5  blockquote modern-quote  avia-builder-el-3  el_before_av_textblock  avia-builder-el-first  "><h5 class="av-special-heading-tag" itemprop="headline">友情链接</h5><div class="special-heading-border"><div class="special-heading-inner-border"></div></div></div>
                <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " style="font-size:14px; " itemprop="text"><p><a href="http://www.xinquanedu.com/">留学中介</a></p>
                        <p><a href="http://www.zxxdh.com/">找学校导航网</a></p>
                        <p><a href="http://www.okliuxue.com/">上海留学中介</a></p>
                        <p><a href="http://www.adh.cn/">澳德华移民</a></p>
                        <p><a href="http://www.51guoji.com/">上海国际学校</a></p>
                    </div></section></div><div class="flex_column av_one_third  no_margin flex_column_div av-zero-column-padding   avia-builder-el-5  el_after_av_one_third  el_before_av_one_third  " style="margin-top:50px; margin-bottom:50px; border-radius:0px; "><div style="padding-bottom:10px;" class="av-special-heading av-special-heading-h5  blockquote modern-quote  avia-builder-el-6  el_before_av_textblock  avia-builder-el-first  "><h5 class="av-special-heading-tag" itemprop="headline">留学益网分支机构</h5><div class="special-heading-border"><div class="special-heading-inner-border"></div></div></div>
                <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " style="font-size:14px; " itemprop="text"><p><a href="http://www.cstudyabroad.com/contact-us/">益网北京</a></p>
                        <p><a href="http://www.cstudyabroad.com/contact-us/">益网悉尼</a></p>
                        <p><a href="http://www.cstudyabroad.com/contact-us/">益网墨尔本</a></p>
                        <p><a href="http://www.cstudyabroad.com/contact-us/">益网霍巴特</a></p>
                    </div></section></div><div class="flex_column av_one_third  no_margin flex_column_div av-zero-column-padding   avia-builder-el-8  el_after_av_one_third  avia-builder-el-last  " style="margin-top:50px; margin-bottom:50px; border-radius:0px; "><div style="padding-bottom:10px;" class="av-special-heading av-special-heading-h5  blockquote modern-quote  avia-builder-el-9  el_before_av_textblock  avia-builder-el-first  "><h5 class="av-special-heading-tag" itemprop="headline">关于我们</h5><div class="special-heading-border"><div class="special-heading-inner-border"></div></div></div>
                <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock " style="font-size:14px; " itemprop="text"><p><a href="http://www.cstudyabroad.com/constant-team/">顾问团队</a></p>
                        <p><a href="http://www.cstudyabroad.com/contract-for-service">服务合约</a></p>
                        <p><a href="http://www.cstudyabroad.com/recruitment">诚聘英才</a></p>
                        <p><a href="http://weibo.com/cstudyabroad">益网微博</a></p>
                    </div></section></div></div></div><div class="flex_cell no_margin av_one_half  avia-builder-el-11  el_after_av_cell_one_half  avia-builder-el-last   av-zero-padding " style="vertical-align:top; padding:0px; "><div class="flex_cell_inner">
            <div class="flex_column av_one_third  no_margin flex_column_div av-zero-column-padding first  avia-builder-el-12  el_before_av_one_third  avia-builder-el-first  " style="margin-top:50px; margin-bottom:50px; border-radius:0px; "><div style="padding-bottom:10px;" class="av-special-heading av-special-heading-h5  blockquote modern-quote  avia-builder-el-13  el_before_av_textblock  avia-builder-el-first  "><h5 class="av-special-heading-tag" itemprop="headline">联系我们</h5><div class="special-heading-border"><div class="special-heading-inner-border"></div></div></div>
                <section class="av_textblock_section" itemscope="itemscope" itemtype="https://schema.org/CreativeWork"><div class="avia_textblock  av_inherit_color" style="font-size:14px; color:#a1b1ed; " itemprop="text"><p><span style="font-size: 24pt;"><strong>400-997-1573</strong></span></p>
                        <p>周一至周六（9:00 – 18:00）</p>
                    </div></section>
                <div class="avia-button-wrap avia-button-left  avia-builder-el-15  el_after_av_textblock  avia-builder-el-last "><a href="http://www.cstudyabroad.com/dialog.htm?arg=9005491&amp;style=1&amp;kflist=on&amp;kf=973248016@qq.com,1793219133@qq.com,297042895@qq.com,1102857630@qq.com,2409737267@qq.com&amp;zdkf_type=1&amp;language=zh-cn&amp;charset=gbk&amp;referer=http%3A%2F%2Fwww.cstudyabroad.com%2Fwht%2Fywkx%2F10017.html&amp;keyword=http%3A%2F%2Fwww.cstudyabroad.com%2Fcsa%2Fmakehtml_list_action.php%3Ftypeid%3D69%26uptype%3Dall%26maxpagesize%3D50%26upnext%3D1%26isremote%3D0%26serviterm%3D&amp;tfrom=1&amp;tpl=crystal_blue" class="avia-button  avia-icon_select-yes-left-icon avia-color-custom avia-size-large avia-position-left " target="_blank" style="background-color:#f36510; border-color:#f36510; color:#ffffff; "><span class="avia_button_icon avia_button_icon_left " aria-hidden="true" data-av_icon="" data-av_iconfont="fontello"></span><span class="avia_iconbox_title">QQ在线咨询</span></a></div></div><div class="flex_column av_one_third  no_margin flex_column_div   avia-builder-el-16  el_after_av_one_third  el_before_av_one_third  " style="margin-top:50px; margin-bottom:50px; padding:20px 0px 0px 0px ; border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-17  avia-builder-el-no-sibling  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/03/csa_footer03.png" alt="" title="csa_footer03" itemprop="thumbnailUrl"></div></div></div><div class="flex_column av_one_third  no_margin flex_column_div   avia-builder-el-18  el_after_av_one_third  avia-builder-el-last  " style="margin-top:50px; margin-bottom:50px; padding:20px 0px 0px 0px ; border-radius:0px; "><div class="avia-image-container  av-styling-   avia-builder-el-19  avia-builder-el-no-sibling  avia-align-center " itemscope="itemscope" itemtype="https://schema.org/ImageObject"><div class="avia-image-container-inner"><img class="avia_image " src="<?php bloginfo('url'); ?>/wp-content/uploads/2017/03/csa_footer04.png" alt="" title="csa_footer04" itemprop="thumbnailUrl"></div></div></div></div></div></div>